AWSTemplateFormatVersion: "2010-09-09"
Description: Creates API Gateway Resource and Method for invoking sftp-user-creation Lambda function.

Parameters:
  pResourceName:
    Type: String
    Description: Prefix for the name of the resources created.
    Default: sftp
  pEnvironment:
    Type: String
    Description: Environment resources are being deployed in.
    ConstraintDescription: Must either be Dev or Prod
    AllowedValues:
      - dev
      - prod
    Default: dev
  pResourceNameApplication:
    Type: String
    Description: Name of integration application.
    Default: servicenow
  pAPIGatewayID:
    Type: String
    Description: RestApiId used for adding to API Gateway.
    Default: REQUIRES INPUT FROM RUNNING api-gateway-data-retrieval.py
  pAPIGatewayRootResourceId:
    Type: String
    Description: API Gateway's Root Resource Id used for the ParentId.
    Default: REQUIRES INPUT FROM RUNNING api-gateway-data-retrieval.py
  pAPIGatewayAuthorizerId:
    Type: String
    Description: Authorizer ideentifier.
    Default: REQUIRES INPUT FROM RUNNING api-gateway-data-retrieval.py
  pSFTPUserCreationLambdaArn:
    Type: String
    Description: Lambda ARN for the sftp-user-creation Lambda function.
    Default: arn:aws:lambda:us-east-2:############:function:dev-ue2-sftp-user-creation

Resources:
  rAPIGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref pAPIGatewayId
      ParentId: !Ref pAPIGatewayRootResourceId
      PathPart: !Ref pResourceName

  rAPIGatewayMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationScopes:
        - application/application.write
      AuthorizationType: COGNITO_USER_POOLS
      AuthorizerId: !Ref pAPIGatewayAuthorizerId
      HttpMethod: POST
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS
        IntegrationResponses:
          - StatusCode: 200
        PassthroughBehvaior: WHEN_NO_TEMPLATES
        Uri: arn:aws:apigateway:us-east-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-2:############:function:dev-ue2-sftp-user-creation/invocations
      MethodReponses:
        - StatusCode: 200
          ResponseModels: { "application/json": "Empty" }
        - StatusCode: 400
      OperationName: !Ref pResourceName
      ResourceId: !Ref rAPIGatewayResource
      RestApiId: !Ref pAPIGatewayId

  rAPIGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - rAPIGatewayMethod
    Properties:
      Description: Deploys API Gateway resource to a stage so ServiceNow can call the API.
      RestApiId: !Ref pAPIGatewayId
      StageName: Dev

  rLambdaAPIGatewayPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref pSFTPUserCreationLambdaArn
      Principal: apigateway.amazonaws.com
      SourceArn: !Join ["". ["arn:aws:execute-api:us-east-2:############:", !Ref pAPIGatewayId, "/*/POST/sftp"]]   